org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.221
loader_version_range=[1,)

mod_id=grappling_hook_neo
mod_name=Grappling Hook: Neo
mod_license=GPL-3.0
mod_version=1.0.1+mc1.21.1
mod_group_id=com.lonevox.grapplinghookneo
mod_authors=Yyon, Nyfaria, Mayesnake, and lonevox
mod_description=GrapplingHook
mod_archive_base=grappling_hook_neo
